# Generated by Codex on 2026-07-18

import re

from django.db import migrations, models


def build_username(email, full_name, user_id):
    base = (email or "").split("@")[0] or full_name or f"user_{user_id}"
    base = re.sub(r"[^a-zA-Z0-9_]+", "_", base).strip("_").lower()
    return (base or f"user_{user_id}")[:140]


def populate_usernames(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen = set()
    for user in User.objects.all().order_by("id"):
        base = build_username(user.email, user.full_name, user.id)
        candidate = base
        suffix = 1
        while candidate.lower() in seen:
            suffix += 1
            tail = f"_{suffix}"
            candidate = f"{base[:150 - len(tail)]}{tail}"
        user.username = candidate
        user.save(update_fields=["username"])
        seen.add(candidate.lower())


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="accounts_us_usernam_c0ea66_idx"),
        ),
    ]
