# Generated by Django 5.2.16 on 2026-07-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_logs__user_id_d31e2a_idx'), models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['entity_type'], name='audit_logs__entity__5f3d85_idx'), models.Index(fields=['created_at'], name='audit_logs__created_0fc90a_idx')],
            },
        ),
    ]
