# Generated by Codex on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("reports", "0002_make_report_task_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_reports",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="time_spent_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
